//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommunicateRESTfulService.SMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://member.smsmkt.com/webservice/", ConfigurationName="SMSService.SMSServicePortType")]
    public interface SMSServicePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message getCreditRemainRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicateRESTfulService.SMSService.getCreditRemainResponse getCreditRemain(SmileSCommunicateRESTfulService.SMSService.getCreditRemainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.getCreditRemainResponse> getCreditRemainAsync(SmileSCommunicateRESTfulService.SMSService.getCreditRemainRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message sendMessageRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicateRESTfulService.SMSService.sendMessageResponse sendMessage(SmileSCommunicateRESTfulService.SMSService.sendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendMessageResponse> sendMessageAsync(SmileSCommunicateRESTfulService.SMSService.sendMessageRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message getDeliveryNotifyRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyResponse getDeliveryNotify(SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyResponse> getDeliveryNotifyAsync(SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message sendSMSFileRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicateRESTfulService.SMSService.sendSMSFileResponse sendSMSFile(SmileSCommunicateRESTfulService.SMSService.sendSMSFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendSMSFileResponse> sendSMSFileAsync(SmileSCommunicateRESTfulService.SMSService.sendSMSFileRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message Delete_ScheduleRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleResponse Delete_Schedule(SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleResponse> Delete_ScheduleAsync(SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message getScheduleDetailRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicateRESTfulService.SMSService.getScheduleDetailResponse getScheduleDetail(SmileSCommunicateRESTfulService.SMSService.getScheduleDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.getScheduleDetailResponse> getScheduleDetailAsync(SmileSCommunicateRESTfulService.SMSService.getScheduleDetailRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message sendMessageUTFRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicateRESTfulService.SMSService.sendMessageUTFResponse sendMessageUTF(SmileSCommunicateRESTfulService.SMSService.sendMessageUTFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendMessageUTFResponse> sendMessageUTFAsync(SmileSCommunicateRESTfulService.SMSService.sendMessageUTFRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message sendSMSFileUTFRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFResponse sendSMSFileUTF(SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFResponse> sendSMSFileUTFAsync(SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message sendMessageSpecialRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialResponse sendMessageSpecial(SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialResponse> sendMessageSpecialAsync(SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreditRemain", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getCreditRemainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        public getCreditRemainRequest() {
        }
        
        public getCreditRemainRequest(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreditRemainResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getCreditRemainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public getCreditRemainResponse() {
        }
        
        public getCreditRemainResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessage", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string SendDate;
        
        public sendMessageRequest() {
        }
        
        public sendMessageRequest(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            this.Username = Username;
            this.Password = Password;
            this.Phone = Phone;
            this.Message = Message;
            this.Sender = Sender;
            this.SendDate = SendDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendMessageResponse() {
        }
        
        public sendMessageResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeliveryNotify", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getDeliveryNotifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Transaction;
        
        public getDeliveryNotifyRequest() {
        }
        
        public getDeliveryNotifyRequest(string Username, string Password, string Transaction) {
            this.Username = Username;
            this.Password = Password;
            this.Transaction = Transaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeliveryNotifyResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getDeliveryNotifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public getDeliveryNotifyResponse() {
        }
        
        public getDeliveryNotifyResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSFile", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendSMSFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string FileData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string SenderName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string SendDate;
        
        public sendSMSFileRequest() {
        }
        
        public sendSMSFileRequest(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            this.Username = Username;
            this.Password = Password;
            this.FileData = FileData;
            this.FileName = FileName;
            this.SenderName = SenderName;
            this.SendDate = SendDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSFileResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendSMSFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendSMSFileResponse() {
        }
        
        public sendSMSFileResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Schedule", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class Delete_ScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Schedule_id;
        
        public Delete_ScheduleRequest() {
        }
        
        public Delete_ScheduleRequest(string Username, string Password, string Schedule_id) {
            this.Username = Username;
            this.Password = Password;
            this.Schedule_id = Schedule_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_ScheduleResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class Delete_ScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public Delete_ScheduleResponse() {
        }
        
        public Delete_ScheduleResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getScheduleDetail", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getScheduleDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Schedule_id;
        
        public getScheduleDetailRequest() {
        }
        
        public getScheduleDetailRequest(string Username, string Password, string Schedule_id) {
            this.Username = Username;
            this.Password = Password;
            this.Schedule_id = Schedule_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getScheduleDetailResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getScheduleDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public getScheduleDetailResponse() {
        }
        
        public getScheduleDetailResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageUTF", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageUTFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string SendDate;
        
        public sendMessageUTFRequest() {
        }
        
        public sendMessageUTFRequest(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            this.Username = Username;
            this.Password = Password;
            this.Phone = Phone;
            this.Message = Message;
            this.Sender = Sender;
            this.SendDate = SendDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageUTFResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageUTFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendMessageUTFResponse() {
        }
        
        public sendMessageUTFResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSFileUTF", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendSMSFileUTFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string FileData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string SenderName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string SendDate;
        
        public sendSMSFileUTFRequest() {
        }
        
        public sendSMSFileUTFRequest(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            this.Username = Username;
            this.Password = Password;
            this.FileData = FileData;
            this.FileName = FileName;
            this.SenderName = SenderName;
            this.SendDate = SendDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSFileUTFResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendSMSFileUTFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendSMSFileUTFResponse() {
        }
        
        public sendSMSFileUTFResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageSpecial", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageSpecialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string DLRcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string BRcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string Message;
        
        public sendMessageSpecialRequest() {
        }
        
        public sendMessageSpecialRequest(string Username, string Password, string DLRcode, string BRcode, string Phone, string Message) {
            this.Username = Username;
            this.Password = Password;
            this.DLRcode = DLRcode;
            this.BRcode = BRcode;
            this.Phone = Phone;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageSpecialResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageSpecialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendMessageSpecialResponse() {
        }
        
        public sendMessageSpecialResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSServicePortTypeChannel : SmileSCommunicateRESTfulService.SMSService.SMSServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServicePortTypeClient : System.ServiceModel.ClientBase<SmileSCommunicateRESTfulService.SMSService.SMSServicePortType>, SmileSCommunicateRESTfulService.SMSService.SMSServicePortType {
        
        public SMSServicePortTypeClient() {
        }
        
        public SMSServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicateRESTfulService.SMSService.getCreditRemainResponse SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.getCreditRemain(SmileSCommunicateRESTfulService.SMSService.getCreditRemainRequest request) {
            return base.Channel.getCreditRemain(request);
        }
        
        public string getCreditRemain(string Username, string Password) {
            SmileSCommunicateRESTfulService.SMSService.getCreditRemainRequest inValue = new SmileSCommunicateRESTfulService.SMSService.getCreditRemainRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            SmileSCommunicateRESTfulService.SMSService.getCreditRemainResponse retVal = ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).getCreditRemain(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.getCreditRemainResponse> SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.getCreditRemainAsync(SmileSCommunicateRESTfulService.SMSService.getCreditRemainRequest request) {
            return base.Channel.getCreditRemainAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.getCreditRemainResponse> getCreditRemainAsync(string Username, string Password) {
            SmileSCommunicateRESTfulService.SMSService.getCreditRemainRequest inValue = new SmileSCommunicateRESTfulService.SMSService.getCreditRemainRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            return ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).getCreditRemainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicateRESTfulService.SMSService.sendMessageResponse SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.sendMessage(SmileSCommunicateRESTfulService.SMSService.sendMessageRequest request) {
            return base.Channel.sendMessage(request);
        }
        
        public string sendMessage(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            SmileSCommunicateRESTfulService.SMSService.sendMessageRequest inValue = new SmileSCommunicateRESTfulService.SMSService.sendMessageRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Phone = Phone;
            inValue.Message = Message;
            inValue.Sender = Sender;
            inValue.SendDate = SendDate;
            SmileSCommunicateRESTfulService.SMSService.sendMessageResponse retVal = ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).sendMessage(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendMessageResponse> SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.sendMessageAsync(SmileSCommunicateRESTfulService.SMSService.sendMessageRequest request) {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendMessageResponse> sendMessageAsync(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            SmileSCommunicateRESTfulService.SMSService.sendMessageRequest inValue = new SmileSCommunicateRESTfulService.SMSService.sendMessageRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Phone = Phone;
            inValue.Message = Message;
            inValue.Sender = Sender;
            inValue.SendDate = SendDate;
            return ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyResponse SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.getDeliveryNotify(SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyRequest request) {
            return base.Channel.getDeliveryNotify(request);
        }
        
        public string getDeliveryNotify(string Username, string Password, string Transaction) {
            SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyRequest inValue = new SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Transaction = Transaction;
            SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyResponse retVal = ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).getDeliveryNotify(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyResponse> SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.getDeliveryNotifyAsync(SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyRequest request) {
            return base.Channel.getDeliveryNotifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyResponse> getDeliveryNotifyAsync(string Username, string Password, string Transaction) {
            SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyRequest inValue = new SmileSCommunicateRESTfulService.SMSService.getDeliveryNotifyRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Transaction = Transaction;
            return ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).getDeliveryNotifyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicateRESTfulService.SMSService.sendSMSFileResponse SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.sendSMSFile(SmileSCommunicateRESTfulService.SMSService.sendSMSFileRequest request) {
            return base.Channel.sendSMSFile(request);
        }
        
        public string sendSMSFile(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            SmileSCommunicateRESTfulService.SMSService.sendSMSFileRequest inValue = new SmileSCommunicateRESTfulService.SMSService.sendSMSFileRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.FileData = FileData;
            inValue.FileName = FileName;
            inValue.SenderName = SenderName;
            inValue.SendDate = SendDate;
            SmileSCommunicateRESTfulService.SMSService.sendSMSFileResponse retVal = ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).sendSMSFile(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendSMSFileResponse> SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.sendSMSFileAsync(SmileSCommunicateRESTfulService.SMSService.sendSMSFileRequest request) {
            return base.Channel.sendSMSFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendSMSFileResponse> sendSMSFileAsync(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            SmileSCommunicateRESTfulService.SMSService.sendSMSFileRequest inValue = new SmileSCommunicateRESTfulService.SMSService.sendSMSFileRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.FileData = FileData;
            inValue.FileName = FileName;
            inValue.SenderName = SenderName;
            inValue.SendDate = SendDate;
            return ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).sendSMSFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleResponse SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.Delete_Schedule(SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleRequest request) {
            return base.Channel.Delete_Schedule(request);
        }
        
        public string Delete_Schedule(string Username, string Password, string Schedule_id) {
            SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleRequest inValue = new SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Schedule_id = Schedule_id;
            SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleResponse retVal = ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).Delete_Schedule(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleResponse> SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.Delete_ScheduleAsync(SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleRequest request) {
            return base.Channel.Delete_ScheduleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleResponse> Delete_ScheduleAsync(string Username, string Password, string Schedule_id) {
            SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleRequest inValue = new SmileSCommunicateRESTfulService.SMSService.Delete_ScheduleRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Schedule_id = Schedule_id;
            return ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).Delete_ScheduleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicateRESTfulService.SMSService.getScheduleDetailResponse SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.getScheduleDetail(SmileSCommunicateRESTfulService.SMSService.getScheduleDetailRequest request) {
            return base.Channel.getScheduleDetail(request);
        }
        
        public string getScheduleDetail(string Username, string Password, string Schedule_id) {
            SmileSCommunicateRESTfulService.SMSService.getScheduleDetailRequest inValue = new SmileSCommunicateRESTfulService.SMSService.getScheduleDetailRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Schedule_id = Schedule_id;
            SmileSCommunicateRESTfulService.SMSService.getScheduleDetailResponse retVal = ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).getScheduleDetail(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.getScheduleDetailResponse> SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.getScheduleDetailAsync(SmileSCommunicateRESTfulService.SMSService.getScheduleDetailRequest request) {
            return base.Channel.getScheduleDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.getScheduleDetailResponse> getScheduleDetailAsync(string Username, string Password, string Schedule_id) {
            SmileSCommunicateRESTfulService.SMSService.getScheduleDetailRequest inValue = new SmileSCommunicateRESTfulService.SMSService.getScheduleDetailRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Schedule_id = Schedule_id;
            return ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).getScheduleDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicateRESTfulService.SMSService.sendMessageUTFResponse SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.sendMessageUTF(SmileSCommunicateRESTfulService.SMSService.sendMessageUTFRequest request) {
            return base.Channel.sendMessageUTF(request);
        }
        
        public string sendMessageUTF(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            SmileSCommunicateRESTfulService.SMSService.sendMessageUTFRequest inValue = new SmileSCommunicateRESTfulService.SMSService.sendMessageUTFRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Phone = Phone;
            inValue.Message = Message;
            inValue.Sender = Sender;
            inValue.SendDate = SendDate;
            SmileSCommunicateRESTfulService.SMSService.sendMessageUTFResponse retVal = ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).sendMessageUTF(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendMessageUTFResponse> SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.sendMessageUTFAsync(SmileSCommunicateRESTfulService.SMSService.sendMessageUTFRequest request) {
            return base.Channel.sendMessageUTFAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendMessageUTFResponse> sendMessageUTFAsync(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            SmileSCommunicateRESTfulService.SMSService.sendMessageUTFRequest inValue = new SmileSCommunicateRESTfulService.SMSService.sendMessageUTFRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Phone = Phone;
            inValue.Message = Message;
            inValue.Sender = Sender;
            inValue.SendDate = SendDate;
            return ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).sendMessageUTFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFResponse SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.sendSMSFileUTF(SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFRequest request) {
            return base.Channel.sendSMSFileUTF(request);
        }
        
        public string sendSMSFileUTF(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFRequest inValue = new SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.FileData = FileData;
            inValue.FileName = FileName;
            inValue.SenderName = SenderName;
            inValue.SendDate = SendDate;
            SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFResponse retVal = ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).sendSMSFileUTF(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFResponse> SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.sendSMSFileUTFAsync(SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFRequest request) {
            return base.Channel.sendSMSFileUTFAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFResponse> sendSMSFileUTFAsync(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFRequest inValue = new SmileSCommunicateRESTfulService.SMSService.sendSMSFileUTFRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.FileData = FileData;
            inValue.FileName = FileName;
            inValue.SenderName = SenderName;
            inValue.SendDate = SendDate;
            return ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).sendSMSFileUTFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialResponse SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.sendMessageSpecial(SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialRequest request) {
            return base.Channel.sendMessageSpecial(request);
        }
        
        public string sendMessageSpecial(string Username, string Password, string DLRcode, string BRcode, string Phone, string Message) {
            SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialRequest inValue = new SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.DLRcode = DLRcode;
            inValue.BRcode = BRcode;
            inValue.Phone = Phone;
            inValue.Message = Message;
            SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialResponse retVal = ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).sendMessageSpecial(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialResponse> SmileSCommunicateRESTfulService.SMSService.SMSServicePortType.sendMessageSpecialAsync(SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialRequest request) {
            return base.Channel.sendMessageSpecialAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialResponse> sendMessageSpecialAsync(string Username, string Password, string DLRcode, string BRcode, string Phone, string Message) {
            SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialRequest inValue = new SmileSCommunicateRESTfulService.SMSService.sendMessageSpecialRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.DLRcode = DLRcode;
            inValue.BRcode = BRcode;
            inValue.Phone = Phone;
            inValue.Message = Message;
            return ((SmileSCommunicateRESTfulService.SMSService.SMSServicePortType)(this)).sendMessageSpecialAsync(inValue);
        }
    }
}
