//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommunicateRESTfulService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_GetDeliveryNotify
    {
        public int Log_id { get; set; }
        public Nullable<System.DateTime> Log_TimeStamp { get; set; }
        public Nullable<bool> Get_Success { get; set; }
    }
}
