//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommunicateRESTfulService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SM()
        {
            this.Receivers = new HashSet<Receiver>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int SMSID { get; set; }
        public string Message { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> SMSTypeID { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> xSMSQueueDetailId { get; set; }
        public Nullable<int> ProviderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receiver> Receivers { get; set; }
        public virtual Section Section { get; set; }
        public virtual Sender Sender { get; set; }
        public virtual SMSType SMSType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
