//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommunicateRESTfulService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int TransactionDetailID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string Detail { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> TransactionDetailStatusID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Credit { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual TransactionDetailStatu TransactionDetailStatu { get; set; }
    }
}
