//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommunicate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CommunicateV1Entities : DbContext
    {
        public CommunicateV1Entities()
            : base("name=CommunicateV1Entities")
        {
            //add 7/1/2020
            var objectContext = (this as IObjectContextAdapter).ObjectContext;
            objectContext.CommandTimeout = 300;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SMSQueueHeader> SMSQueueHeader { get; set; }
        public virtual DbSet<Receiver> Receiver { get; set; }
        public virtual DbSet<SMS> SMS { get; set; }
        public virtual DbSet<SMSQueueSent> SMSQueueSent { get; set; }
        public virtual DbSet<TransactionStatus> TransactionStatus { get; set; }
        public virtual DbSet<TransactionHeader> TransactionHeader { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<SMSQueueDetail> SMSQueueDetail { get; set; }
    
        public virtual ObjectResult<usp_GetListSMSType_Select_Result> usp_GetListSMSType_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetListSMSType_Select_Result>("usp_GetListSMSType_Select");
        }
    
        public virtual ObjectResult<usp_TransactionDetail_Select_Result> usp_TransactionDetail_Select(Nullable<int> pTransactionID)
        {
            var pTransactionIDParameter = pTransactionID.HasValue ?
                new ObjectParameter("pTransactionID", pTransactionID) :
                new ObjectParameter("pTransactionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TransactionDetail_Select_Result>("usp_TransactionDetail_Select", pTransactionIDParameter);
        }
    
        public virtual ObjectResult<usp_TransactionNotGetDeliveryNotify_Select_Result> usp_TransactionNotGetDeliveryNotify_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TransactionNotGetDeliveryNotify_Select_Result>("usp_TransactionNotGetDeliveryNotify_Select");
        }
    
        public virtual ObjectResult<usp_TransactionDetailStatus_Select_Result> usp_TransactionDetailStatus_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TransactionDetailStatus_Select_Result>("usp_TransactionDetailStatus_Select");
        }
    
        public virtual ObjectResult<usp_TransactionStatus_Select_Result> usp_TransactionStatus_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TransactionStatus_Select_Result>("usp_TransactionStatus_Select");
        }
    
        public virtual ObjectResult<usp_GetListSMSReport_Select_Result> usp_GetListSMSReport_Select(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> sMSTypeId, Nullable<int> transactionStatusId, Nullable<int> transactionDetailStatusId, string criteria, Nullable<int> pageStart, Nullable<int> pageSize, string sortField, string orderType)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var sMSTypeIdParameter = sMSTypeId.HasValue ?
                new ObjectParameter("SMSTypeId", sMSTypeId) :
                new ObjectParameter("SMSTypeId", typeof(int));
    
            var transactionStatusIdParameter = transactionStatusId.HasValue ?
                new ObjectParameter("TransactionStatusId", transactionStatusId) :
                new ObjectParameter("TransactionStatusId", typeof(int));
    
            var transactionDetailStatusIdParameter = transactionDetailStatusId.HasValue ?
                new ObjectParameter("TransactionDetailStatusId", transactionDetailStatusId) :
                new ObjectParameter("TransactionDetailStatusId", typeof(int));
    
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            var pageStartParameter = pageStart.HasValue ?
                new ObjectParameter("PageStart", pageStart) :
                new ObjectParameter("PageStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetListSMSReport_Select_Result>("usp_GetListSMSReport_Select", startDateParameter, endDateParameter, sMSTypeIdParameter, transactionStatusIdParameter, transactionDetailStatusIdParameter, criteriaParameter, pageStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter);
        }
    
        public virtual ObjectResult<usp_SMSQueueDetail_Select_Result> usp_SMSQueueDetail_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SMSQueueDetail_Select_Result>("usp_SMSQueueDetail_Select");
        }
    
        public virtual ObjectResult<usp_TransactionGetDeliveryNotify_Select_Result> usp_TransactionGetDeliveryNotify_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TransactionGetDeliveryNotify_Select_Result>("usp_TransactionGetDeliveryNotify_Select");
        }
    
        public virtual int usp_TransactionGetDeliveryNotify_Update(string referenceID, string xMLResult)
        {
            var referenceIDParameter = referenceID != null ?
                new ObjectParameter("ReferenceID", referenceID) :
                new ObjectParameter("ReferenceID", typeof(string));
    
            var xMLResultParameter = xMLResult != null ?
                new ObjectParameter("XMLResult", xMLResult) :
                new ObjectParameter("XMLResult", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_TransactionGetDeliveryNotify_Update", referenceIDParameter, xMLResultParameter);
        }
    
        public virtual ObjectResult<usp_SendSMS_Insert_Result> usp_SendSMS_Insert(Nullable<int> sMSQueueSentId, Nullable<int> createdById, Nullable<int> senderID)
        {
            var sMSQueueSentIdParameter = sMSQueueSentId.HasValue ?
                new ObjectParameter("SMSQueueSentId", sMSQueueSentId) :
                new ObjectParameter("SMSQueueSentId", typeof(int));
    
            var createdByIdParameter = createdById.HasValue ?
                new ObjectParameter("CreatedById", createdById) :
                new ObjectParameter("CreatedById", typeof(int));
    
            var senderIDParameter = senderID.HasValue ?
                new ObjectParameter("SenderID", senderID) :
                new ObjectParameter("SenderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SendSMS_Insert_Result>("usp_SendSMS_Insert", sMSQueueSentIdParameter, createdByIdParameter, senderIDParameter);
        }
    
        public virtual ObjectResult<usp_TransactionHeader_Update_Result> usp_TransactionHeader_Update(Nullable<int> transactionHeaderId, string xMLReturn)
        {
            var transactionHeaderIdParameter = transactionHeaderId.HasValue ?
                new ObjectParameter("TransactionHeaderId", transactionHeaderId) :
                new ObjectParameter("TransactionHeaderId", typeof(int));
    
            var xMLReturnParameter = xMLReturn != null ?
                new ObjectParameter("XMLReturn", xMLReturn) :
                new ObjectParameter("XMLReturn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TransactionHeader_Update_Result>("usp_TransactionHeader_Update", transactionHeaderIdParameter, xMLReturnParameter);
        }
    
        public virtual ObjectResult<usp_TmpSMSToSMSQueue_Insert_Result> usp_TmpSMSToSMSQueue_Insert(Nullable<int> tmpSMSHeaderId, Nullable<System.DateTime> sentDate, string remark, Nullable<int> createdByUserId)
        {
            var tmpSMSHeaderIdParameter = tmpSMSHeaderId.HasValue ?
                new ObjectParameter("TmpSMSHeaderId", tmpSMSHeaderId) :
                new ObjectParameter("TmpSMSHeaderId", typeof(int));
    
            var sentDateParameter = sentDate.HasValue ?
                new ObjectParameter("SentDate", sentDate) :
                new ObjectParameter("SentDate", typeof(System.DateTime));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("Remark", remark) :
                new ObjectParameter("Remark", typeof(string));
    
            var createdByUserIdParameter = createdByUserId.HasValue ?
                new ObjectParameter("CreatedByUserId", createdByUserId) :
                new ObjectParameter("CreatedByUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TmpSMSToSMSQueue_Insert_Result>("usp_TmpSMSToSMSQueue_Insert", tmpSMSHeaderIdParameter, sentDateParameter, remarkParameter, createdByUserIdParameter);
        }
    
        public virtual ObjectResult<usp_SMSTypeForSemiAuto_Select_Result> usp_SMSTypeForSemiAuto_Select(Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SMSTypeForSemiAuto_Select_Result>("usp_SMSTypeForSemiAuto_Select", indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_SMSTypeXPaymethodType_Select_Result> usp_SMSTypeXPaymethodType_Select(Nullable<int> sMSTypeId, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var sMSTypeIdParameter = sMSTypeId.HasValue ?
                new ObjectParameter("SMSTypeId", sMSTypeId) :
                new ObjectParameter("SMSTypeId", typeof(int));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SMSTypeXPaymethodType_Select_Result>("usp_SMSTypeXPaymethodType_Select", sMSTypeIdParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_SMSDetail_Select_Result1> usp_SMSDetail_Select(string code, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SMSDetail_Select_Result1>("usp_SMSDetail_Select", codeParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_SMSSubDetail_Select_Result1> usp_SMSSubDetail_Select(string code, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SMSSubDetail_Select_Result1>("usp_SMSSubDetail_Select", codeParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_GetSMSTypeIdByCode_Select(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_GetSMSTypeIdByCode_Select", codeParameter);
        }
    
        public virtual ObjectResult<usp_InsertSMSDetail_SEMI_Insert_Result> usp_InsertSMSDetail_SEMI_Insert(Nullable<System.DateTime> period, Nullable<int> sMSTypeId, Nullable<int> paymethodId, string remark, Nullable<int> createdByUserId)
        {
            var periodParameter = period.HasValue ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(System.DateTime));
    
            var sMSTypeIdParameter = sMSTypeId.HasValue ?
                new ObjectParameter("SMSTypeId", sMSTypeId) :
                new ObjectParameter("SMSTypeId", typeof(int));
    
            var paymethodIdParameter = paymethodId.HasValue ?
                new ObjectParameter("PaymethodId", paymethodId) :
                new ObjectParameter("PaymethodId", typeof(int));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("Remark", remark) :
                new ObjectParameter("Remark", typeof(string));
    
            var createdByUserIdParameter = createdByUserId.HasValue ?
                new ObjectParameter("CreatedByUserId", createdByUserId) :
                new ObjectParameter("CreatedByUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_InsertSMSDetail_SEMI_Insert_Result>("usp_InsertSMSDetail_SEMI_Insert", periodParameter, sMSTypeIdParameter, paymethodIdParameter, remarkParameter, createdByUserIdParameter);
        }
    
        public virtual ObjectResult<usp_TmpSMS_Delete_Result> usp_TmpSMS_Delete(Nullable<int> tmpSMSHeaderId, Nullable<int> updatedByUserId)
        {
            var tmpSMSHeaderIdParameter = tmpSMSHeaderId.HasValue ?
                new ObjectParameter("TmpSMSHeaderId", tmpSMSHeaderId) :
                new ObjectParameter("TmpSMSHeaderId", typeof(int));
    
            var updatedByUserIdParameter = updatedByUserId.HasValue ?
                new ObjectParameter("UpdatedByUserId", updatedByUserId) :
                new ObjectParameter("UpdatedByUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TmpSMS_Delete_Result>("usp_TmpSMS_Delete", tmpSMSHeaderIdParameter, updatedByUserIdParameter);
        }
    
        public virtual ObjectResult<usp_TmpSMSHeader_Select_Result> usp_TmpSMSHeader_Select(Nullable<int> tmpSMSHeaderId, Nullable<System.DateTime> period, Nullable<int> indexStart, Nullable<int> pageSize, string sortField, string orderType, string searchDetail)
        {
            var tmpSMSHeaderIdParameter = tmpSMSHeaderId.HasValue ?
                new ObjectParameter("TmpSMSHeaderId", tmpSMSHeaderId) :
                new ObjectParameter("TmpSMSHeaderId", typeof(int));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(System.DateTime));
    
            var indexStartParameter = indexStart.HasValue ?
                new ObjectParameter("IndexStart", indexStart) :
                new ObjectParameter("IndexStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            var searchDetailParameter = searchDetail != null ?
                new ObjectParameter("SearchDetail", searchDetail) :
                new ObjectParameter("SearchDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TmpSMSHeader_Select_Result>("usp_TmpSMSHeader_Select", tmpSMSHeaderIdParameter, periodParameter, indexStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter, searchDetailParameter);
        }
    
        public virtual ObjectResult<usp_Report_SMSDetail_Select_Result> usp_Report_SMSDetail_Select(Nullable<int> tmpSMSHeaderId)
        {
            var tmpSMSHeaderIdParameter = tmpSMSHeaderId.HasValue ?
                new ObjectParameter("TmpSMSHeaderId", tmpSMSHeaderId) :
                new ObjectParameter("TmpSMSHeaderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Report_SMSDetail_Select_Result>("usp_Report_SMSDetail_Select", tmpSMSHeaderIdParameter);
        }
    
        public virtual ObjectResult<usp_Report_SMSSubDetail_Select_Result> usp_Report_SMSSubDetail_Select(Nullable<int> tmpSMSHeaderId)
        {
            var tmpSMSHeaderIdParameter = tmpSMSHeaderId.HasValue ?
                new ObjectParameter("TmpSMSHeaderId", tmpSMSHeaderId) :
                new ObjectParameter("TmpSMSHeaderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Report_SMSSubDetail_Select_Result>("usp_Report_SMSSubDetail_Select", tmpSMSHeaderIdParameter);
        }
    
        public virtual ObjectResult<usp_Transaction_select_Result> usp_Transaction_select(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> sMSTypeId, string criteria, Nullable<int> pageStart, Nullable<int> pageSize, string sortField, string orderType)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var sMSTypeIdParameter = sMSTypeId.HasValue ?
                new ObjectParameter("SMSTypeId", sMSTypeId) :
                new ObjectParameter("SMSTypeId", typeof(int));
    
            var criteriaParameter = criteria != null ?
                new ObjectParameter("Criteria", criteria) :
                new ObjectParameter("Criteria", typeof(string));
    
            var pageStartParameter = pageStart.HasValue ?
                new ObjectParameter("PageStart", pageStart) :
                new ObjectParameter("PageStart", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortFieldParameter = sortField != null ?
                new ObjectParameter("SortField", sortField) :
                new ObjectParameter("SortField", typeof(string));
    
            var orderTypeParameter = orderType != null ?
                new ObjectParameter("OrderType", orderType) :
                new ObjectParameter("OrderType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Transaction_select_Result>("usp_Transaction_select", startDateParameter, endDateParameter, sMSTypeIdParameter, criteriaParameter, pageStartParameter, pageSizeParameter, sortFieldParameter, orderTypeParameter);
        }
    }
}
