//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommunicate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> TransactionHeaderId { get; set; }
        public Nullable<int> SMSID { get; set; }
        public Nullable<int> TransactionStatusID { get; set; }
        public string ReferenceID { get; set; }
        public Nullable<int> SumPhone { get; set; }
        public Nullable<int> UsedCredit { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> GetDeliveryNotify { get; set; }
        public Nullable<System.DateTime> SendingStatusUpdateDate { get; set; }
        public string Success { get; set; }
        public string Fail { get; set; }
        public string Block { get; set; }
        public string Expired { get; set; }
        public string Processing { get; set; }
        public string Unknown { get; set; }
        public string XMLResult { get; set; }
        public Nullable<int> Credit { get; set; }
    
        public virtual SMS SMS { get; set; }
        public virtual TransactionStatus TransactionStatus { get; set; }
    }
}
