//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileSCommunicate.SmsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://member.smsmkt.com/webservice/", ConfigurationName="SmsServiceReference.SMSServicePortType")]
    public interface SMSServicePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message getCreditRemainRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicate.SmsServiceReference.getCreditRemainResponse getCreditRemain(SmileSCommunicate.SmsServiceReference.getCreditRemainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.getCreditRemainResponse> getCreditRemainAsync(SmileSCommunicate.SmsServiceReference.getCreditRemainRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message sendMessageRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicate.SmsServiceReference.sendMessageResponse sendMessage(SmileSCommunicate.SmsServiceReference.sendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendMessageResponse> sendMessageAsync(SmileSCommunicate.SmsServiceReference.sendMessageRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message getDeliveryNotifyRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicate.SmsServiceReference.getDeliveryNotifyResponse getDeliveryNotify(SmileSCommunicate.SmsServiceReference.getDeliveryNotifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.getDeliveryNotifyResponse> getDeliveryNotifyAsync(SmileSCommunicate.SmsServiceReference.getDeliveryNotifyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message sendSMSFileRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicate.SmsServiceReference.sendSMSFileResponse sendSMSFile(SmileSCommunicate.SmsServiceReference.sendSMSFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendSMSFileResponse> sendSMSFileAsync(SmileSCommunicate.SmsServiceReference.sendSMSFileRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message Delete_ScheduleRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicate.SmsServiceReference.Delete_ScheduleResponse Delete_Schedule(SmileSCommunicate.SmsServiceReference.Delete_ScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.Delete_ScheduleResponse> Delete_ScheduleAsync(SmileSCommunicate.SmsServiceReference.Delete_ScheduleRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message getScheduleDetailRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicate.SmsServiceReference.getScheduleDetailResponse getScheduleDetail(SmileSCommunicate.SmsServiceReference.getScheduleDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.getScheduleDetailResponse> getScheduleDetailAsync(SmileSCommunicate.SmsServiceReference.getScheduleDetailRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message sendMessageUTFRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicate.SmsServiceReference.sendMessageUTFResponse sendMessageUTF(SmileSCommunicate.SmsServiceReference.sendMessageUTFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendMessageUTFResponse> sendMessageUTFAsync(SmileSCommunicate.SmsServiceReference.sendMessageUTFRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message sendSMSFileUTFRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicate.SmsServiceReference.sendSMSFileUTFResponse sendSMSFileUTF(SmileSCommunicate.SmsServiceReference.sendSMSFileUTFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendSMSFileUTFResponse> sendSMSFileUTFAsync(SmileSCommunicate.SmsServiceReference.sendSMSFileUTFRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://member.smsmkt.com/webservice/) of message sendMessageSpecialRequest does not match the default value (https://member.smsmkt.com/webservice/)
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SmileSCommunicate.SmsServiceReference.sendMessageSpecialResponse sendMessageSpecial(SmileSCommunicate.SmsServiceReference.sendMessageSpecialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://member.smsmkt.com/webservice/", ReplyAction="*")]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendMessageSpecialResponse> sendMessageSpecialAsync(SmileSCommunicate.SmsServiceReference.sendMessageSpecialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreditRemain", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getCreditRemainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        public getCreditRemainRequest() {
        }
        
        public getCreditRemainRequest(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCreditRemainResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getCreditRemainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public getCreditRemainResponse() {
        }
        
        public getCreditRemainResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessage", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string SendDate;
        
        public sendMessageRequest() {
        }
        
        public sendMessageRequest(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            this.Username = Username;
            this.Password = Password;
            this.Phone = Phone;
            this.Message = Message;
            this.Sender = Sender;
            this.SendDate = SendDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendMessageResponse() {
        }
        
        public sendMessageResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeliveryNotify", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getDeliveryNotifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Transaction;
        
        public getDeliveryNotifyRequest() {
        }
        
        public getDeliveryNotifyRequest(string Username, string Password, string Transaction) {
            this.Username = Username;
            this.Password = Password;
            this.Transaction = Transaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeliveryNotifyResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getDeliveryNotifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public getDeliveryNotifyResponse() {
        }
        
        public getDeliveryNotifyResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSFile", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendSMSFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string FileData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string SenderName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string SendDate;
        
        public sendSMSFileRequest() {
        }
        
        public sendSMSFileRequest(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            this.Username = Username;
            this.Password = Password;
            this.FileData = FileData;
            this.FileName = FileName;
            this.SenderName = SenderName;
            this.SendDate = SendDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSFileResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendSMSFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendSMSFileResponse() {
        }
        
        public sendSMSFileResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Schedule", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class Delete_ScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Schedule_id;
        
        public Delete_ScheduleRequest() {
        }
        
        public Delete_ScheduleRequest(string Username, string Password, string Schedule_id) {
            this.Username = Username;
            this.Password = Password;
            this.Schedule_id = Schedule_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_ScheduleResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class Delete_ScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public Delete_ScheduleResponse() {
        }
        
        public Delete_ScheduleResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getScheduleDetail", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getScheduleDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Schedule_id;
        
        public getScheduleDetailRequest() {
        }
        
        public getScheduleDetailRequest(string Username, string Password, string Schedule_id) {
            this.Username = Username;
            this.Password = Password;
            this.Schedule_id = Schedule_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getScheduleDetailResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class getScheduleDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public getScheduleDetailResponse() {
        }
        
        public getScheduleDetailResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageUTF", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageUTFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string SendDate;
        
        public sendMessageUTFRequest() {
        }
        
        public sendMessageUTFRequest(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            this.Username = Username;
            this.Password = Password;
            this.Phone = Phone;
            this.Message = Message;
            this.Sender = Sender;
            this.SendDate = SendDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageUTFResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageUTFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendMessageUTFResponse() {
        }
        
        public sendMessageUTFResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSFileUTF", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendSMSFileUTFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string FileData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string SenderName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string SendDate;
        
        public sendSMSFileUTFRequest() {
        }
        
        public sendSMSFileUTFRequest(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            this.Username = Username;
            this.Password = Password;
            this.FileData = FileData;
            this.FileName = FileName;
            this.SenderName = SenderName;
            this.SendDate = SendDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSFileUTFResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendSMSFileUTFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendSMSFileUTFResponse() {
        }
        
        public sendSMSFileUTFResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageSpecial", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageSpecialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string DLRcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string BRcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string Message;
        
        public sendMessageSpecialRequest() {
        }
        
        public sendMessageSpecialRequest(string Username, string Password, string DLRcode, string BRcode, string Phone, string Message) {
            this.Username = Username;
            this.Password = Password;
            this.DLRcode = DLRcode;
            this.BRcode = BRcode;
            this.Phone = Phone;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageSpecialResponse", WrapperNamespace="http://member.smsmkt.com/webservice/", IsWrapped=true)]
    public partial class sendMessageSpecialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public sendMessageSpecialResponse() {
        }
        
        public sendMessageSpecialResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSServicePortTypeChannel : SmileSCommunicate.SmsServiceReference.SMSServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServicePortTypeClient : System.ServiceModel.ClientBase<SmileSCommunicate.SmsServiceReference.SMSServicePortType>, SmileSCommunicate.SmsServiceReference.SMSServicePortType {
        
        public SMSServicePortTypeClient() {
        }
        
        public SMSServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicate.SmsServiceReference.getCreditRemainResponse SmileSCommunicate.SmsServiceReference.SMSServicePortType.getCreditRemain(SmileSCommunicate.SmsServiceReference.getCreditRemainRequest request) {
            return base.Channel.getCreditRemain(request);
        }
        
        public string getCreditRemain(string Username, string Password) {
            SmileSCommunicate.SmsServiceReference.getCreditRemainRequest inValue = new SmileSCommunicate.SmsServiceReference.getCreditRemainRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            SmileSCommunicate.SmsServiceReference.getCreditRemainResponse retVal = ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).getCreditRemain(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.getCreditRemainResponse> SmileSCommunicate.SmsServiceReference.SMSServicePortType.getCreditRemainAsync(SmileSCommunicate.SmsServiceReference.getCreditRemainRequest request) {
            return base.Channel.getCreditRemainAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.getCreditRemainResponse> getCreditRemainAsync(string Username, string Password) {
            SmileSCommunicate.SmsServiceReference.getCreditRemainRequest inValue = new SmileSCommunicate.SmsServiceReference.getCreditRemainRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            return ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).getCreditRemainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicate.SmsServiceReference.sendMessageResponse SmileSCommunicate.SmsServiceReference.SMSServicePortType.sendMessage(SmileSCommunicate.SmsServiceReference.sendMessageRequest request) {
            return base.Channel.sendMessage(request);
        }
        
        public string sendMessage(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            SmileSCommunicate.SmsServiceReference.sendMessageRequest inValue = new SmileSCommunicate.SmsServiceReference.sendMessageRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Phone = Phone;
            inValue.Message = Message;
            inValue.Sender = Sender;
            inValue.SendDate = SendDate;
            SmileSCommunicate.SmsServiceReference.sendMessageResponse retVal = ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).sendMessage(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendMessageResponse> SmileSCommunicate.SmsServiceReference.SMSServicePortType.sendMessageAsync(SmileSCommunicate.SmsServiceReference.sendMessageRequest request) {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendMessageResponse> sendMessageAsync(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            SmileSCommunicate.SmsServiceReference.sendMessageRequest inValue = new SmileSCommunicate.SmsServiceReference.sendMessageRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Phone = Phone;
            inValue.Message = Message;
            inValue.Sender = Sender;
            inValue.SendDate = SendDate;
            return ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicate.SmsServiceReference.getDeliveryNotifyResponse SmileSCommunicate.SmsServiceReference.SMSServicePortType.getDeliveryNotify(SmileSCommunicate.SmsServiceReference.getDeliveryNotifyRequest request) {
            return base.Channel.getDeliveryNotify(request);
        }
        
        public string getDeliveryNotify(string Username, string Password, string Transaction) {
            SmileSCommunicate.SmsServiceReference.getDeliveryNotifyRequest inValue = new SmileSCommunicate.SmsServiceReference.getDeliveryNotifyRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Transaction = Transaction;
            SmileSCommunicate.SmsServiceReference.getDeliveryNotifyResponse retVal = ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).getDeliveryNotify(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.getDeliveryNotifyResponse> SmileSCommunicate.SmsServiceReference.SMSServicePortType.getDeliveryNotifyAsync(SmileSCommunicate.SmsServiceReference.getDeliveryNotifyRequest request) {
            return base.Channel.getDeliveryNotifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.getDeliveryNotifyResponse> getDeliveryNotifyAsync(string Username, string Password, string Transaction) {
            SmileSCommunicate.SmsServiceReference.getDeliveryNotifyRequest inValue = new SmileSCommunicate.SmsServiceReference.getDeliveryNotifyRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Transaction = Transaction;
            return ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).getDeliveryNotifyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicate.SmsServiceReference.sendSMSFileResponse SmileSCommunicate.SmsServiceReference.SMSServicePortType.sendSMSFile(SmileSCommunicate.SmsServiceReference.sendSMSFileRequest request) {
            return base.Channel.sendSMSFile(request);
        }
        
        public string sendSMSFile(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            SmileSCommunicate.SmsServiceReference.sendSMSFileRequest inValue = new SmileSCommunicate.SmsServiceReference.sendSMSFileRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.FileData = FileData;
            inValue.FileName = FileName;
            inValue.SenderName = SenderName;
            inValue.SendDate = SendDate;
            SmileSCommunicate.SmsServiceReference.sendSMSFileResponse retVal = ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).sendSMSFile(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendSMSFileResponse> SmileSCommunicate.SmsServiceReference.SMSServicePortType.sendSMSFileAsync(SmileSCommunicate.SmsServiceReference.sendSMSFileRequest request) {
            return base.Channel.sendSMSFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendSMSFileResponse> sendSMSFileAsync(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            SmileSCommunicate.SmsServiceReference.sendSMSFileRequest inValue = new SmileSCommunicate.SmsServiceReference.sendSMSFileRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.FileData = FileData;
            inValue.FileName = FileName;
            inValue.SenderName = SenderName;
            inValue.SendDate = SendDate;
            return ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).sendSMSFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicate.SmsServiceReference.Delete_ScheduleResponse SmileSCommunicate.SmsServiceReference.SMSServicePortType.Delete_Schedule(SmileSCommunicate.SmsServiceReference.Delete_ScheduleRequest request) {
            return base.Channel.Delete_Schedule(request);
        }
        
        public string Delete_Schedule(string Username, string Password, string Schedule_id) {
            SmileSCommunicate.SmsServiceReference.Delete_ScheduleRequest inValue = new SmileSCommunicate.SmsServiceReference.Delete_ScheduleRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Schedule_id = Schedule_id;
            SmileSCommunicate.SmsServiceReference.Delete_ScheduleResponse retVal = ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).Delete_Schedule(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.Delete_ScheduleResponse> SmileSCommunicate.SmsServiceReference.SMSServicePortType.Delete_ScheduleAsync(SmileSCommunicate.SmsServiceReference.Delete_ScheduleRequest request) {
            return base.Channel.Delete_ScheduleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.Delete_ScheduleResponse> Delete_ScheduleAsync(string Username, string Password, string Schedule_id) {
            SmileSCommunicate.SmsServiceReference.Delete_ScheduleRequest inValue = new SmileSCommunicate.SmsServiceReference.Delete_ScheduleRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Schedule_id = Schedule_id;
            return ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).Delete_ScheduleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicate.SmsServiceReference.getScheduleDetailResponse SmileSCommunicate.SmsServiceReference.SMSServicePortType.getScheduleDetail(SmileSCommunicate.SmsServiceReference.getScheduleDetailRequest request) {
            return base.Channel.getScheduleDetail(request);
        }
        
        public string getScheduleDetail(string Username, string Password, string Schedule_id) {
            SmileSCommunicate.SmsServiceReference.getScheduleDetailRequest inValue = new SmileSCommunicate.SmsServiceReference.getScheduleDetailRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Schedule_id = Schedule_id;
            SmileSCommunicate.SmsServiceReference.getScheduleDetailResponse retVal = ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).getScheduleDetail(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.getScheduleDetailResponse> SmileSCommunicate.SmsServiceReference.SMSServicePortType.getScheduleDetailAsync(SmileSCommunicate.SmsServiceReference.getScheduleDetailRequest request) {
            return base.Channel.getScheduleDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.getScheduleDetailResponse> getScheduleDetailAsync(string Username, string Password, string Schedule_id) {
            SmileSCommunicate.SmsServiceReference.getScheduleDetailRequest inValue = new SmileSCommunicate.SmsServiceReference.getScheduleDetailRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Schedule_id = Schedule_id;
            return ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).getScheduleDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicate.SmsServiceReference.sendMessageUTFResponse SmileSCommunicate.SmsServiceReference.SMSServicePortType.sendMessageUTF(SmileSCommunicate.SmsServiceReference.sendMessageUTFRequest request) {
            return base.Channel.sendMessageUTF(request);
        }
        
        public string sendMessageUTF(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            SmileSCommunicate.SmsServiceReference.sendMessageUTFRequest inValue = new SmileSCommunicate.SmsServiceReference.sendMessageUTFRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Phone = Phone;
            inValue.Message = Message;
            inValue.Sender = Sender;
            inValue.SendDate = SendDate;
            SmileSCommunicate.SmsServiceReference.sendMessageUTFResponse retVal = ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).sendMessageUTF(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendMessageUTFResponse> SmileSCommunicate.SmsServiceReference.SMSServicePortType.sendMessageUTFAsync(SmileSCommunicate.SmsServiceReference.sendMessageUTFRequest request) {
            return base.Channel.sendMessageUTFAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendMessageUTFResponse> sendMessageUTFAsync(string Username, string Password, string Phone, string Message, string Sender, string SendDate) {
            SmileSCommunicate.SmsServiceReference.sendMessageUTFRequest inValue = new SmileSCommunicate.SmsServiceReference.sendMessageUTFRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.Phone = Phone;
            inValue.Message = Message;
            inValue.Sender = Sender;
            inValue.SendDate = SendDate;
            return ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).sendMessageUTFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicate.SmsServiceReference.sendSMSFileUTFResponse SmileSCommunicate.SmsServiceReference.SMSServicePortType.sendSMSFileUTF(SmileSCommunicate.SmsServiceReference.sendSMSFileUTFRequest request) {
            return base.Channel.sendSMSFileUTF(request);
        }
        
        public string sendSMSFileUTF(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            SmileSCommunicate.SmsServiceReference.sendSMSFileUTFRequest inValue = new SmileSCommunicate.SmsServiceReference.sendSMSFileUTFRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.FileData = FileData;
            inValue.FileName = FileName;
            inValue.SenderName = SenderName;
            inValue.SendDate = SendDate;
            SmileSCommunicate.SmsServiceReference.sendSMSFileUTFResponse retVal = ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).sendSMSFileUTF(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendSMSFileUTFResponse> SmileSCommunicate.SmsServiceReference.SMSServicePortType.sendSMSFileUTFAsync(SmileSCommunicate.SmsServiceReference.sendSMSFileUTFRequest request) {
            return base.Channel.sendSMSFileUTFAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendSMSFileUTFResponse> sendSMSFileUTFAsync(string Username, string Password, string FileData, string FileName, string SenderName, string SendDate) {
            SmileSCommunicate.SmsServiceReference.sendSMSFileUTFRequest inValue = new SmileSCommunicate.SmsServiceReference.sendSMSFileUTFRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.FileData = FileData;
            inValue.FileName = FileName;
            inValue.SenderName = SenderName;
            inValue.SendDate = SendDate;
            return ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).sendSMSFileUTFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmileSCommunicate.SmsServiceReference.sendMessageSpecialResponse SmileSCommunicate.SmsServiceReference.SMSServicePortType.sendMessageSpecial(SmileSCommunicate.SmsServiceReference.sendMessageSpecialRequest request) {
            return base.Channel.sendMessageSpecial(request);
        }
        
        public string sendMessageSpecial(string Username, string Password, string DLRcode, string BRcode, string Phone, string Message) {
            SmileSCommunicate.SmsServiceReference.sendMessageSpecialRequest inValue = new SmileSCommunicate.SmsServiceReference.sendMessageSpecialRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.DLRcode = DLRcode;
            inValue.BRcode = BRcode;
            inValue.Phone = Phone;
            inValue.Message = Message;
            SmileSCommunicate.SmsServiceReference.sendMessageSpecialResponse retVal = ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).sendMessageSpecial(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendMessageSpecialResponse> SmileSCommunicate.SmsServiceReference.SMSServicePortType.sendMessageSpecialAsync(SmileSCommunicate.SmsServiceReference.sendMessageSpecialRequest request) {
            return base.Channel.sendMessageSpecialAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmileSCommunicate.SmsServiceReference.sendMessageSpecialResponse> sendMessageSpecialAsync(string Username, string Password, string DLRcode, string BRcode, string Phone, string Message) {
            SmileSCommunicate.SmsServiceReference.sendMessageSpecialRequest inValue = new SmileSCommunicate.SmsServiceReference.sendMessageSpecialRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.DLRcode = DLRcode;
            inValue.BRcode = BRcode;
            inValue.Phone = Phone;
            inValue.Message = Message;
            return ((SmileSCommunicate.SmsServiceReference.SMSServicePortType)(this)).sendMessageSpecialAsync(inValue);
        }
    }
}
